# deploys to the main site from master

name: Deploy to Firebase Hosting from master
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@master
        with:
          node-version: '14.x'
      
      - name: Install expo
        run: npm i -g expo-cli

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: expo build:web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOOD_7953D }}'
          channelId: live
          projectId: mood-7953d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
